name: Deploy Astro to GitHub Pages

on:
  # Löst den Workflow bei einem Push auf den main-Branch aus
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22.9.0'  # Empfohlen für Astro

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist  # Hier sicherstellen, dass das dist-Verzeichnis verwendet wird
          force_orphan: true 